/*
 * generated by Xtext
 */
package org.euro2016;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntitiesRuntimeModule extends org.euro2016.AbstractEntitiesRuntimeModule {

}
